apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-microservice-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-microservice
      environment: blue
  template:
    metadata:
      labels:
        app: rust-microservice
        environment: blue
    spec:
      containers:
        - name: rust-microservice
          image: devnullaccount/rust-microservice:blue
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
