apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rust-microservice-hpa
  namespace: my-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-microservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
