apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-microservice-blue
  namespace: my-namespace
  labels:
    app: rust-microservice
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-microservice
      version: blue
  template:
    metadata:
      labels:
        app: rust-microservice
        version: blue
    spec:
      containers:
        - name: rust-microservice
          image: devnullaccount/rust-microservice:blue
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
