name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust project
        run: cargo build --release

      - name: Run Rust tests
        run: cargo test --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t devnullaccount/rust-microservice:latest \
                        -t devnullaccount/rust-microservice:${{ env.COMMIT_SHA }} .

      - name: Push Docker images
        run: |
          docker push devnullaccount/rust-microservice:latest
          docker push devnullaccount/rust-microservice:${{ env.COMMIT_SHA }}

      - name: Image digest
        id: image-digest
        run: echo "digest=$(docker inspect --format='{{index .RepoDigests 0}}' devnullaccount/rust-microservice:latest)" >> $GITHUB_ENV

      - name: Print image digest
        run: echo "The Docker image digest is ${{ env.digest }}"
      
      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create and push Git tag
      env:
        GITHUB_TOKEN: ${{ secrets.MY_CUSTOM_TOKEN }}
      run: |
        git tag -a "v${{ github.run_number }}" -m "Release version ${{ github.run_number }}"
        git push origin "v${{ github.run_number }}"
